---
#
# Installing Filebeat
#

# Download SSL certificate:

- name: Download certificate
  shell: wget https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
  
# Create directory for certification

- name: Make new directory for cert
  shell: mkdir -p /etc/pki/tls/certs
  
# Move cert to directory

- name: Move SSL certification to new folder
  shell: cp COMODORSADomainValidationSecureServerCA.crt /etc/pki/tls/certs/

- name: Download Filebeat RPM package
  uri:
    url: "{{ filebeat_rpm_url | default('https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.3.1-x86_64.rpm') }}"
    dest: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}"

- name: Install Filebeat.
  yum:
    name: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}/{{ filebeat_rpm_package | default('filebeat-6.3.1-x86_64.rpm') }}"
    state: installed
  register: rpm_installation
  
# Replace Filebeat configuration to ship to Logz.io. 

- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
