---
#
# Installing Java 8
#
- name: Redhat | Check oracle jdk package
  stat:
    path: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}/{{ oracle_jdk_rpm_package | default('jdk-8u144-linux-x64.rpm') }}"
  register: rpm_package

- name: RedHat | Download Oracle JDK RPM package
  uri:
    url: "{{ oracle_jdk_rpm_url | default('http://download.oracle.com/otn-pub/java/jdk/8u144-b01/jdk-8u144-linux-x64.rpm') }}"
    dest: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}"
    HEADER_Cookie: 'gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

# Install/Configure Java package(s)

- name: RedHat | Install Java Oracle
  yum:
    name: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}/{{ oracle_jdk_rpm_package | default('jdk-8u144-linux-x64.rpm') }}"
    state: installed
  register: rpm_installation

- name: RedHat | Get Oracle jdk package version
  shell: "rpm -qip {{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}/{{ oracle_jdk_rpm_package | default('jdk-8u144-linux-x64.rpm') }} | grep 'Version' | awk '{print $NF}'"
  register: jdk_rpm_package_version