---
#
# Installing Elasticsearch
#

# Installing Elasticsearch

- name: Install Elasticsearch
  yum:
   name: elasticsearch
   update_cache: yes
   
# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost'). 

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'
 
# Update Elasticsearch port in config file 

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'
 
# Start Elasticsearch
- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started
    
